version: "3.7"
services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      TZ: UTC
      MYSQL_ROOT_PASSWORD: db123
    volumes:
      - ./docker/mariadb/data:/var/lib/mysql
      - ./docker/mariadb/log:/var/log/mysql
      - ./docker/mariadb/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    networks:
      - ais-network
  cache:
    image: redis/redis-stack:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_ARGS=--requirepass redis123
    volumes:
      - ./docker/redis/data:/data
    networks:
      - ais-network
volumes:
  ais-data:
networks:
  ais-network:
    driver: bridge
